version: '3.8'

services:
  bolt:
    image: node:18
    container_name: bolt_app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
